djangoshop1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import Home
from customer.views import LoginView, logout_view
from customer.views import SingUp
from order.views import CartItemAPI, ShowCart, remove_cartitem, empty_car, Checkout
from product.views import ProductCategory


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('singup/', SingUp.as_view(), name='sing_up'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('category/<category_slug>', ProductCategory.as_view(), name='categoryproducts'),
    path('add-cartitem/', CartItemAPI.as_view(), name='add_cartitem'),
    path('cart/', ShowCart.as_view(), name='cart'),
    path('remove_cartitem/', remove_cartitem, name='remove_cartitem'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('empty/', empty_car, name='empty_cart'),
    path('products/', include("product.url")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                           document_root=settings.STATIC_ROOT)

product/models.py
from django.db import models
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _
# Create your models here.


class Category(BaseModel):
    name = models.CharField(max_length=64)
    ccategory = models.ManyToManyField('self', null=True, blank=True)
    category_slug = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی'

    def __str__(self):
        return self.name


class Product(BaseModel):
    name = models.CharField(max_length=64)
    image = models.FileField(null=True)
    price = models.PositiveIntegerField()
    pcategory = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    brand = models.CharField(max_length=64, null=True, blank=True)
    amount = models.PositiveIntegerField()
    slug = models.CharField(max_length=64, unique=True)
    description = models.TextField(null=True, blank=True)
    # discount = models.PositiveIntegerField(null=True, blank=True)
    product_property = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.name


class Discount(models.Model):
    amount = models.IntegerField(null=True, blank=True)
    discount_cod = models.CharField(max_length=10, null=True)
    dcategory = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    dproduct = models.OneToOneField(Product, on_delete=models.CASCADE, null=True, blank=True, related_name='discount' ,related_query_name='discount')
    percentage = models.FloatField(null=True, blank=True)

    class Meta:
        verbose_name = 'تخفیف'
        verbose_name_plural = 'تخفیفات'

    def aplly_discount(self):

        if self.dproduct and self.percentage:
            discountprice= self.dproduct.price * (self.percentage)
            return float(discountprice)


    # def __str__(self):
    #     return self.aplly_discount


class Comments(BaseModel):
    name = models.CharField(max_length=64, null=True, blank=True)
    email = models.EmailField()
    comment = models.TextField(null=True, blank=True)

product/views.py
from typing import Generic

from django.shortcuts import render

# Create your views here.
from django.views import View
# from django.views.generic.list import ListView
from django.views.generic import DetailView, ListView

from .filters import CategoryFilter
from .models import Product, Discount, Category
from order.models import Cart, CartItem


class ProductDetail(DetailView):
    model = Product
    template_name = 'product1.html'


class ProductList(ListView):
    model = Product
    template_name = 'products.html'


class ProductCategory(View):
    def get(self, request, category_slug):
        category = Category.objects.get(category_slug=category_slug)
        products = Product.objects.all()
        list_products = []
        for product in products:
            if product.pcategory == category:
                list_products.append(product)
        return render(request, 'category.html', {'products': list_products})



def category(request):
    if request.method == "GET":
        categorys = Category.objects.all()
        products = Product.objects.all()
        categorylist = []
        for category in categorys:
            category.name = []
            for product in products:
                if product.pcategory == category:
                    category.name.append(product)

            categorylist.append(category.name)

        contex = {'categorys': categorylist}
        render(request, 'categury.html', context=contex)

templates/__base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/themify-icons.css">
    <link rel="stylesheet" href="/static/fonts/flaticon.css">

        <link rel="stylesheet" href="/static/css/magnific-popup.css">

    <!--owl carousel -->
    <link href="/static/css/owl.theme.default.min.css" rel="stylesheet">
    <link href="/static/css/owl.carousel.min.css" rel="stylesheet">

    <!-- bootstrap core css -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- custom css -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/style1.css" rel="stylesheet">
    <link href="/static/iofrm-style-1.css" rel="stylesheet">


    <!-- responsive css -->
    <link href="/static/css/responsive.css" rel="stylesheet">
</head>
<body>
<header class="header">
                <!--start navbar-->
                <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
                    <div class="container">
                        <a class="navbar-brand" href="#">
                            <img src="../static/img/logo.png" alt="">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar"
                            aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="form-inline my-2 my-lg-0">

                            <p id="cart-total">0</p>
                  <a href="#cart">
                      <img src="../static/img/cart.png" alt="cart" id="cart-icon">
                  </a>
                            <a href="#" class="btn btn-primary">Login</a>


              </div>
                        <div class="collapse navbar-collapse" id="myNavbar">
                            <ul class="nav navbar-nav mr-auto navbar-right">
                                <li class="active"><a class="page-scroll" href="#hero">خانه</a></li>
                                <li><a class="page-scroll" href="#products">محصولات</a></li>
                                <li><a class="page-scroll" href="#features">ویژگی ها</a></li>
                                <li><a class="page-scroll" href="#faqs">پرسش و پاسخ</a></li>
                                <li><a class="page-scroll" href="#contact">تماس با ما</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!--end navbar-->
            </header>
<div>
{% block content %}

{% endblock %}
</div>

<script src="../static/js/jquery-3.3.1.min.js"></script>

    <!-- bootstrap core js -->
<script src="../static/js/bootstrap.min.js"></script>
<script src="../static/js/scripts.js"></script>



{% block jscript %}

{% endblock %}
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">

        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <!--owl carousel -->
    <link href="/{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- bootstrap core css -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- custom css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'style1.css' %}" rel="stylesheet">
    <link href="{% static 'iofrm-style-1.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'css/css/style.css' %}" rel="stylesheet" />


    <!-- responsive css -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <script>
$(document).ready(function(){
  $("h3").click(function(event){
    $("h3").hide();
  });
});
</script>
</head>
<body>
<header class="header">
                <!--start navbar-->
                <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
                    <div class="container">
                        <a class="navbar-brand" href="#">
                            <img src="img/logo.png" alt="">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar"
                            aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="form-inline my-2 my-lg-0">

{#                            <p id="cart-total">0</p>#}
                  <a href="{% url 'cart' %}">
                      <img src="/static/img/cart.png" alt="cart" id="cart-icon">
                  </a>
                            {% block login %}<a href="#" class="btn btn-primary"></a>{% endblock %}


              </div>
                        <div class="collapse navbar-collapse" id="myNavbar">
                            <ul class="nav navbar-nav mr-auto navbar-right">
                                <li class="active"><a class="page-scroll" href="{% url 'home' %}">خانه</a></li>
                                <li><a class="page-scroll" href="{% url 'products:list_product' %}">محصولات</a></li>
                                <li><a class="page-scroll" href="#features">ویژگی ها</a></li>
                                <li><a class="page-scroll" href="#faqs">پرسش و پاسخ</a></li>
                                <li><a class="page-scroll" href="#contact">تماس با ما</a></li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!--end navbar-->
            </header>

{% block content %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
<script>
    {#$("#logout").click(function(){#}
    {#    let xhttp = new XMLHttpRequest();#}
    {#    let url = "{% url 'logout' %}"#}
    {#    xhttp.onload = function() {#}
    {#       console.log(this.state)#}
    {#        console.log(this.status)#}
    {#        console.log(this.response)#}
    {#}#}
    {#xhttp.open("GET", url);#}
    {#xhttp.send();#}
    {# $("#logout").hide();#}
    {#    $("#login").show();#}
    {# });#}
</script>
{% block jscript %}
{% endblock %}

</body>
</html>

templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>cart item</h1>
</body>
</html>

templates/cartpage.html
{% extends 'base.html' %}
{% block login %}
    {% if user.username %}
{#        {% user.customer = cusrtomer %}#}
        <a href="{% url 'logout' %}" class="btn btn-primary">خروج</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-primary">ورود</a>
    {% endif %}
{% endblock %}
{% block content %}
{% if cart %}
        <div class="content" style="margin-top: 100px">
		<h1>سبد خرید</h1>
        <a class="btn btn-danger" id="remove_all" href="">خالی کردن سبدخرید</a>
		<p>تعداد محصولات را اضافه و کم کنید و سبد خود را آپدیت کنید.</p>
		<!-- start undo button -->
		<p class="removeAlert">
			آیتم مورد نظر حذف شد. اشتباه کردید؟ <a href="#">برگرداندن آیتم</a>
		</p>
		<!-- end undo button -->


		<table class="items">
			<thead>
			<!-- start table head -->
			<tr>
				<th>نام محصول</th>
				<th>قیمت</th>
				<th>تعداد</th>
				<th>مجموع</th>
			</tr>
			<!-- end table head -->
			</thead>
			<tbody>
            {% for cart_item in cartitems %}
                {% if cart_item.cart == cart %}
                    			<!-- start table body -->
			<tr>
				<!-- start item one -->
				<td>
					<div class="item">
						<div class="item-front">
							<img src="{{ cart_item.product.image.url }}" />
						</div>
						<div class="item-back">
							<img src="{{ cart_item.product.image.url }}" />
						</div>
					</div>
					<p>{{ cart_item.product.name }}<br /><span class="itemNum">A5 2017</span></p>
					<p class="description">خلاصه توضیح در مورد محصول مورد نظر</p>
				</td>
				<td>{{ cart_item.product.price }}</td>
				<td>
                    <a class="btn btn-danger minus" id="kam">-</a>
                    <a  id="count-{{ cart_item.id }}" dproduct="{{ cart_item.id }}" price="{{ cart_item.price }}" class="btn btn-info" >{{ cart_item.count }}</a>
                    <a class="btn btn-success plus" id="ezafeh">+</a>
					<a href="#" class="remove" cartitemid="{{ cart_item.id }}">حذف</a>
				</td>
				<td class="itemTotal">{{ cart_item.total_price }}</td>
				<!-- end item one -->
			</tr>
                {% endif %}
            {% endfor %}
			</tbody>
		</table>

		<!-- start checkout list -->
		<div class="cost">
			<h2>پیش فاکتور</h2>

			<table class="pricing">
				<tbody>
				<tr>
					<td>قیمت کل</td>
					<td class="subtotal"><del>{{ cart.total_price }}</del></td>
				</tr>
				<tr>
					<td>تخفیف</td>
					<td class="tax"></td>
				</tr>
				<tr>
					<td><strong>مجموع:</strong></td>
					<td class="orderTotal">{{ cart.total_price }}</td>
				</tr>
				</tbody>
			</table>
                <a type="submit" class="col-10 btn btn-info" id="buy" href="{% url 'checkout' %}">خرید</a>

		</div><!-- end checkout list -->
	</div> <!-- End Content -->
{% else %}
    <div class="content d-flex justify-content-center" style="margin-top: 100px">
<h1>سبد خرید خالی ست</h1>
    </div>
{% endif %}

{% endblock %}
{% block jscript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
    $('#remove_all').click(function () {
       $(this).hide()
           var json = JSON.stringify({'cart':{{cart.id}}})
        console.log(json)
      $.ajax({
    type: "POST",
    url: "{% url 'empty_cart' %}",
    data: json,
    headers: {
           'X-CSRFToken': "{{ csrf_token }}"
         },
contentType: "application/json",
success: function (msg) {
    console.log(msg)
    console.log(json)
    console.log(this.response)
console.log('success')
location.reload()
},
error: function (msg) {
alert("error");
console.log(msg)
}
});
    });


$(".minus").click(function(){
    var x=Number($(this).parent("td").children(".btn-info").text())-1
    $(this).parent("td").children(".btn-info").text(x)
    var y = $(this).parent("td").children(".btn-info").attr("dproduct")
    var z = Number($(this).parent("td").children(".btn-info").attr("price"))
           var json = JSON.stringify({"product":Number(y), "count": x, 'price': z, 'cart':{{cart.id}}})
      $.ajax({
    type: "POST",
    url: "{% url 'add_cartitem' %}",
    data: json,
    headers: {
           'X-CSRFToken': "{{ csrf_token }}"
         },
contentType: "application/json",
success: function (msg) {
    console.log(msg)
    console.log(json)
    console.log(this.response)
console.log('success')
location.reload()
},
error: function (msg) {
alert("error");
}
});


});
$(".plus").click(function(){
    var x=Number($(this).parent("td").children(".btn-info").text())+1
    var y = $(this).parent("td").children(".btn-info").attr("dproduct")
    var z = Number($(this).parent("td").children(".btn-info").attr("price"))
           var json = JSON.stringify({"product":Number(y), "count": x, 'price': z, 'cart':{{cart.id}}})
      $.ajax({
    type: "POST",
    url: "{% url 'add_cartitem' %}",
    data: json,
    headers: {
           'X-CSRFToken': "{{ csrf_token }}"
         },
contentType: "application/json",
success: function (msg) {
    console.log(msg)
    console.log(json)
    console.log(this.response)
    console.log('success')
location.reload()
},
error: function (msg) {
alert("error");
}
});
    $(this).parent("td").children(".btn-info").text(x)
    console.log(y)
});


$('.remove').click(function () {
    var cart_item=$(this).attr('cartitemid')
    console.log(cart_item)
               var json = JSON.stringify({'id':cart_item})
      $.ajax({
    type: "POST",
    url: "{% url 'remove_cartitem' %}",
    data: json,
    headers: {
           'X-CSRFToken': "{{ csrf_token }}"
         },
contentType: "application/json",
success: function (msg) {
    console.log(msg)
    console.log(json)
    console.log(this.response)
    console.log('success')
location.reload()
},
error: function (msg) {
alert("error");
}
});
    $(this).parent('td').hide()
});
    </script>
{% endblock %}

templates/cartt.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a href="" class="btn btn-outline-dark">
                &#x2190  continue shopping
                </a>
                <br><br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>3</strong></h5></th>
                        <th><h5>Total: <strong>42$</strong></h5></th>
                        <th>
                            <a href="{% url 'checkout' %}" class="btn btn-success" style="float: right; margin: 5px;">
                                chekcout
                            </a>
                        </th>
                    </tr>
                </table>
            </div>

         <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex: 2;"></div>
                    <div style="flex: 2;"><strong>Item</strong></div>
                    <div style="flex: 1;"><strong>Price</strong></div>
                    <div style="flex: 1;"><strong>Quantity</strong></div>
                    <div style="flex: 1;"><strong>Total</strong></div>
                </div>
                <div class="cart-row">
                    <div style="flex: 2;"><img src="" alt="" class="row-image"></div>
                    <div style="flex: 2;"><p>product1</p></div>
                    <div style="flex: 1;"><p>$20</p></div>
                    <div style="flex: 1;"><p class="quantity">2</p></div>
                    <div style="flex: 1;"><p>$32</p></div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/category.html
{% extends 'base.html' %}
{% block login %}
    {% if user.username %}
        <a href="{% url 'login' %}" class="btn btn-primary">خروج</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-primary">ورود</a>
    {% endif %}
{% endblock %}
{% block content %}
    {% for product in products %}
        <p>{{ product.name }}</p>
    {% endfor %}

    <div class="biz-product-wrap">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-6">
                                <div class="text-center section-heading" style="color: white">
                                    <h1 style="color: white">fdsafsfafs</h1>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                                          <div style="background-color:#007bff" class="col-12">

                    </div>
                            <div class="col-md-12">
                                <div class="owl-carousel owl-theme biz-products carousel-indicator owl-rtl owl-loaded owl-drag">


                                    {% for product in products %}
                                        <div class="owl-item cloned" style="width: 255px; margin-left: 30px;"><div class="biz-single-product item">
                                        <div class="biz-product-img">
                                            <img src="{{ product.image.url }}" alt="Smart Product" class="img-responsive">
                                        </div>
                                        <div class="biz-product-content">
                                            <p>{{ product.name }}</p>
                                            {% if discount %}
                                                {% for dis in discount %}
                                                    {% if dis.dproduct == product %}
                                                    <div class="price">
                                                        <h5><span class="original-price">{{ product.price }} هزار تومان</span> <del>400 هزار تومان</del></h5>
                                                    </div>
                                                {% else %}
                                                    <div class="price">
                                                <h5><span class="original-price">{{ product.price }} هزار تومان</span></h5>
                                            </div>
                                                {% endif %}
                                            {% endfor %}
                                                {% else %}
                                                           <div class="price">
                                                <h5><span class="original-price">{{ product.price }} هزار تومان</span></h5>
                                            </div>
                                            {% endif %}
                                            <div class="product-action-btn text-center mt-20">
                                                <a href="{% url 'products:product' product_slug=product.slug %}" class="btn softo-btn-outline popup-details">مشاهده جزئیات</a>
                                            </div>
                                        </div>
                                    </div></div>
                                    {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
    </div>
{% endblock %}

templates/categury.html
{% extends 'base.html' %}
{% block login %}
    {% if user.username %}
        <a href="{% url 'login' %}" class="btn btn-primary">خروج</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-primary">ورود</a>
    {% endif %}
{% endblock %}
{% block content %}
    {% for prodct in product_listu %}
        <p>{{ product.name }}</p>
    {% endfor %}

    <div class="biz-product-wrap">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-md-6">
                                <div class="text-center section-heading" style="color: white">
                                    <h1 style="color: white">fdsafsfafs</h1>
                                </div>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-md-12">
                                <div class="owl-carousel owl-theme biz-products carousel-indicator owl-rtl owl-loaded owl-drag">


                                    {% for product in product_list %}
                                        <div class="owl-item cloned" style="width: 255px; margin-left: 30px;"><div class="biz-single-product item">
                                        <div class="biz-product-img">
                                            <img src="{{ product.image.url }}" alt="Smart Product" class="img-responsive">
                                        </div>
                                        <div class="biz-product-content">
                                            <p>{{ product.name }}</p>
                                            {% if discount %}
                                                {% for dis in discount %}
                                                    {% if dis.dproduct == product %}
                                                    <div class="price">
                                                        <h5><span class="original-price">{{ product.price }} هزار تومان</span> <del>400 هزار تومان</del></h5>
                                                    </div>
                                                {% else %}
                                                    <div class="price">
                                                <h5><span class="original-price">{{ product.price }} هزار تومان</span></h5>
                                            </div>
                                                {% endif %}
                                            {% endfor %}
                                                {% else %}
                                                           <div class="price">
                                                <h5><span class="original-price">{{ product.price }} هزار تومان</span></h5>
                                            </div>
                                            {% endif %}
                                            <div class="product-action-btn text-center mt-20">
                                                <a href="{% url 'products:product' slug=product.slug %}" class="btn softo-btn-outline popup-details">مشاهده جزئیات</a>
                                            </div>
                                        </div>
                                    </div></div>
                                    {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
    </div>
{% endblock %}
{% block jscript %}
<script>
    $(document).ready(function(){
    $("label").hide();
    $("#label_category").show();


});
</script>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% block content %}
    <div class="row" style="margin-top: 100px">
      <div class="col-lg-6" >
          <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required name="name" type="text" class="form-control" placeholder="نام...">
                    </div>
                   <div class="form-field">
                    <input required name="email" type="text" class="form-control" placeholder="ایمیل ...">
                   </div>

                </div>
                <div id="shipping-info">
                    <hr>
                    <p>اطلاعات خرید:</p>
                    <hr>
                    <div class="form-field-col d-flex flex-column">
                    <input type="checkbox" value="sdsdfsfdds">
                    <input type="checkbox" value="sdsdfsfdds">
                    <input type="checkbox" value="sdsdfsfdds">
                    <input type="checkbox" value="sdsdfsfdds">
                    <input type="checkbox" value="sdsdfsfdds">
{#                        <button class="add-address">add new address</button>#}

                    </div>
                    <div class="form-field">
                        <input required name="address" type="text" class="form-control" placeholder="ادرس...">
                    </div>
                    <div class="form-field">
                        <input required name="city" type="text" class="form-control" placeholder="شهر...">
                    </div>
                    <div class="form-field">
                        <input required name="state" type="text" class="form-control" placeholder="استان...">
                    </div>
{#                    <div class="form-field">#}
{#                        <input required name="zipcode" type="text" class="form-control" placeholder="Zip Code...">#}
{#                    </div>#}
                    <button class="add-address">add new address</button>
                </div>
                <hr>
                <div class="box-element hidden">
                    <small>Paypal Options</small>

                </div>
                <br>
                <input id="form-button" type="submit" class="btn btn-success btn-block" value="Continue">
            </form>
          </div>
      </div>
      <div class="col-lg-6">
        <div class="box-element">
            <a href="" class="btn btn-outline-dark">
               &#x2190; بازگشت به سبد خرید
            </a>
            <hr>
            <h3>خلاصه سفارش</h3>
            <hr>

            {% for cart_item in cartitems %}
            <div class="cart-row">

                <div style="flex:2">
                    <img src="{{cart_item.product.image.url }}" alt="product" class="row-image">
                </div>
                <div style="flex:2">
                    <p>{{ cart_item.product.name }}</p>
                </div>
                <div style="flex:1">
                    <p>{{ cart_item.price }}</p>
                </div>
                <div style="flex:1">
                    <p>{{ cart_item.count }}</p>
                </div>

            </div>
            {% endfor %}

            <h5>ایتم ها:</h5>
            <h5>قیمت نهایی:{{ cart.total_price }}</h5>
        </div>
    </div>
  </div>

{% endblock %}
{% block jscript %}
<script>
{#$(document).ready(function(){#}
{#    $(".form-field").hide()#}
{#      $(".add-address").click(function(){#}
{#        $(".form-field").show();#}
{#         $(".add-address").hide()#}
{# });#}
{# });#}

</script>
{% endblock %}

templates/product detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for p in product_list %}
    {{ p.name }}
               <form action="{% url 'products:list_product' %}">
                            <label for="id_pcategory" id="label_category" style="color: white"> فیلتر دسته بندی</label>
                            {{ categorys.form }}
                        <input type="submit">
               </form>
{% endfor %}
</body>
</html>